CREATE SCHEMA [adm]
GO

CREATE TABLE [adm].[DOMFIC](
	[DOMFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICEST] [char](1) NOT NULL,
	[DOMFICORD] [int] NULL,
	[DOMFICNOM] [varchar](100) NOT NULL,
	[DOMFICPAT] [varchar](100) NULL,
	[DOMFICVAL] [char](20) NOT NULL,
	[DOMFICOBS] [varchar](5120) NULL,
	[DOMFICAUS] [char](20) NOT NULL,
	[DOMFICAFH] [datetime] NOT NULL,
	[DOMFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_DOMFICCOD] PRIMARY KEY CLUSTERED ([DOMFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMFICA](
	[DOMFICACOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICAMET] [char](20) NOT NULL,
	[DOMFICAUSU] [char](20) NOT NULL,
	[DOMFICAFEC] [datetime] NOT NULL,
	[DOMFICADIP] [char](20) NOT NULL,
	[DOMFICACODOLD] [int] NULL,
	[DOMFICAESTOLD] [char](1) NULL,
	[DOMFICAORDOLD] [int] NULL,
	[DOMFICANOMOLD] [varchar](100) NULL,
	[DOMFICAPATOLD] [varchar](100) NULL,
	[DOMFICAVALOLD] [char](20) NULL,
	[DOMFICAOBSOLD] [varchar](5120) NULL,
	[DOMFICACODNEW] [int] NULL,
	[DOMFICAESTNEW] [char](1) NULL,
	[DOMFICAORDNEW] [int] NULL,
	[DOMFICANOMNEW] [varchar](100) NULL,
	[DOMFICAPATNEW] [varchar](100) NULL,
	[DOMFICAVALNEW] [char](20) NULL,
	[DOMFICAOBSNEW] [varchar](5120) NULL,
 CONSTRAINT [PK_DOMFICACOD] PRIMARY KEY CLUSTERED ([DOMFICACOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMSUB](
	[DOMSUBCOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMSUBEST] [char](1) NOT NULL,
	[DOMSUBTIC] [int] NOT NULL,
	[DOMSUBORD] [int] NULL,
	[DOMSUBNOM] [varchar](100) NOT NULL,
	[DOMSUBPAT] [varchar](100) NULL,
	[DOMSUBVAL] [char](20) NOT NULL,
	[DOMSUBOBS] [varchar](5120) NULL,
	[DOMSUBAUS] [char](20) NOT NULL,
	[DOMSUBAFH] [datetime] NOT NULL,
	[DOMSUBAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_DOMSUBCOD] PRIMARY KEY CLUSTERED ([DOMSUBCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMSUBA](
	[DOMSUBACOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMSUBAMET] [char](20) NOT NULL,
	[DOMSUBAUSU] [char](20) NOT NULL,
	[DOMSUBAFEC] [datetime] NOT NULL,
	[DOMSUBADIP] [char](20) NOT NULL,
	[DOMSUBACODOLD] [int] NULL,
	[DOMSUBAESTOLD] [char](1) NULL,
	[DOMSUBATICOLD] [int] NULL,
	[DOMSUBAORDOLD] [int] NULL,
	[DOMSUBANOMOLD] [varchar](100) NULL,
	[DOMSUBAPATOLD] [varchar](100) NULL,
	[DOMSUBAVALOLD] [char](20) NULL,
	[DOMSUBAOBSOLD] [varchar](5120) NULL,
	[DOMSUBACODNEW] [int] NULL,
	[DOMSUBAESTNEW] [char](1) NULL,
	[DOMSUBATICNEW] [int] NULL,
	[DOMSUBAORDNEW] [int] NULL,
	[DOMSUBANOMNEW] [varchar](100) NULL,
	[DOMSUBAPATNEW] [varchar](100) NULL,
	[DOMSUBAVALNEW] [char](20) NULL,
	[DOMSUBAOBSNEW] [varchar](5120) NULL,
 CONSTRAINT [PK_DOMSUBACOD] PRIMARY KEY CLUSTERED ([DOMSUBACOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [adm].[DOMSUB] WITH CHECK ADD CONSTRAINT [FK_DOMSUB_DOMSUBTIC] FOREIGN KEY([DOMSUBTIC]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[DOMSUB] CHECK CONSTRAINT [FK_DOMSUB_DOMSUBTIC]
GO