CREATE SCHEMA [adm]
GO

CREATE TABLE [adm].[DOMFIC](
	[DOMFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICEST] [char](1) NOT NULL,
	[DOMFICORD] [int] NULL,
	[DOMFICNOI] [varchar](100) NOT NULL,
	[DOMFICNOC] [varchar](100) NOT NULL,
	[DOMFICNOP] [varchar](100) NOT NULL,
	[DOMFICPAT] [varchar](100) NULL,
	[DOMFICVAL] [char](20) NOT NULL,
	[DOMFICOBS] [varchar](5120) NULL,
	[DOMFICAUS] [char](50) NOT NULL,
	[DOMFICAFH] [datetime] NOT NULL,
	[DOMFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_DOMFICCOD] PRIMARY KEY CLUSTERED ([DOMFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMFICA](
	[DOMFICAIDD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICAMET] [char](20) NOT NULL,
	[DOMFICAUSU] [char](50) NOT NULL,
	[DOMFICAFEC] [datetime] NOT NULL,
	[DOMFICADIP] [char](20) NOT NULL,
	[DOMFICACOD] [int] NULL,
	[DOMFICAEST] [char](1) NULL,
	[DOMFICAORD] [int] NULL,
	[DOMFICANOI] [varchar](100) NULL,
	[DOMFICANOC] [varchar](100) NULL,
	[DOMFICANOP] [varchar](100) NULL,
	[DOMFICAPAT] [varchar](100) NULL,
	[DOMFICAVAL] [char](20) NULL,
	[DOMFICAOBS] [varchar](5120) NULL,
 CONSTRAINT [PK_DOMFICAIDD] PRIMARY KEY CLUSTERED ([DOMFICAIDD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TRIGGER [adm].[DOMFIC_INSERT] 
	ON [adm].[DOMFIC]
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMFICA] (DOMFICAMET, DOMFICAUSU, DOMFICAFEC, DOMFICADIP, DOMFICACOD, DOMFICAEST, DOMFICAORD, DOMFICANOI, DOMFICANOC, DOMFICANOP, DOMFICAPAT, DOMFICAVAL, DOMFICAOBS)
		SELECT 'INSERT AFTER', i.DOMFICAUS, GETDATE(), i.DOMFICAIP, i.DOMFICCOD, i.DOMFICEST, i.DOMFICORD, i.DOMFICNOI, i.DOMFICNOC, i.DOMFICNOP, i.DOMFICPAT, i.DOMFICVAL, i.DOMFICOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[DOMFIC_UPDATE] 
	ON [adm].[DOMFIC]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMFICA] (DOMFICAMET, DOMFICAUSU, DOMFICAFEC, DOMFICADIP, DOMFICACOD, DOMFICAEST, DOMFICAORD, DOMFICANOI, DOMFICANOC, DOMFICANOP, DOMFICAPAT, DOMFICAVAL, DOMFICAOBS)
		SELECT 'UPDATE BEFORE', d.DOMFICAUS, GETDATE(), d.DOMFICAIP, d.DOMFICCOD, d.DOMFICEST, d.DOMFICORD, d.DOMFICNOI, d.DOMFICNOC, d.DOMFICNOP, d.DOMFICPAT, d.DOMFICVAL, d.DOMFICOBS FROM DELETED d;

		INSERT INTO [adm].[DOMFICA] (DOMFICAMET, DOMFICAUSU, DOMFICAFEC, DOMFICADIP, DOMFICACOD, DOMFICAEST, DOMFICAORD, DOMFICANOI, DOMFICANOC, DOMFICANOP, DOMFICAPAT, DOMFICAVAL, DOMFICAOBS)
		SELECT 'UPDATE AFTER', i.DOMFICAUS, GETDATE(), i.DOMFICAIP, i.DOMFICCOD, i.DOMFICEST, i.DOMFICORD, i.DOMFICNOI, i.DOMFICNOC, i.DOMFICNOP, i.DOMFICPAT, i.DOMFICVAL, i.DOMFICOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[DOMFIC_DELETE] 
	ON [adm].[DOMFIC]
	AFTER DELETE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMFICA] (DOMFICAMET, DOMFICAUSU, DOMFICAFEC, DOMFICADIP, DOMFICACOD, DOMFICAEST, DOMFICAORD, DOMFICANOI, DOMFICANOC, DOMFICANOP, DOMFICAPAT, DOMFICAVAL, DOMFICAOBS)
		SELECT 'DELETE BEFORE', d.DOMFICAUS, GETDATE(), d.DOMFICAIP, d.DOMFICCOD, d.DOMFICEST, d.DOMFICORD, d.DOMFICNOI, d.DOMFICNOC, d.DOMFICNOP, d.DOMFICPAT, d.DOMFICVAL, d.DOMFICOBS FROM DELETED d;
	END
GO

CREATE TABLE [adm].[DOMSUB](
	[DOMSUBCOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMSUBEST] [char](1) NOT NULL,
	[DOMSUBTIC] [int] NOT NULL,
	[DOMSUBORD] [int] NULL,
	[DOMSUBNOI] [varchar](100) NOT NULL,
	[DOMSUBNOC] [varchar](100) NOT NULL,
	[DOMSUBNOP] [varchar](100) NOT NULL,
	[DOMSUBPAT] [varchar](100) NULL,
	[DOMSUBVAL] [char](20) NOT NULL,
	[DOMSUBOBS] [varchar](5120) NULL,
	[DOMSUBAUS] [char](50) NOT NULL,
	[DOMSUBAFH] [datetime] NOT NULL,
	[DOMSUBAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_DOMSUBCOD] PRIMARY KEY CLUSTERED ([DOMSUBCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMSUBA](
	[DOMSUBAIDD] [int] IDENTITY(1,1) NOT NULL,
	[DOMSUBAMET] [char](20) NOT NULL,
	[DOMSUBAUSU] [char](50) NOT NULL,
	[DOMSUBAFEC] [datetime] NOT NULL,
	[DOMSUBADIP] [char](20) NOT NULL,
	[DOMSUBACOD] [int] NULL,
	[DOMSUBAEST] [char](1) NULL,
	[DOMSUBATIC] [int] NULL,
	[DOMSUBAORD] [int] NULL,
	[DOMSUBANOI] [varchar](100) NULL,
	[DOMSUBANOC] [varchar](100) NULL,
	[DOMSUBANOP] [varchar](100) NULL,
	[DOMSUBAPAT] [varchar](100) NULL,
	[DOMSUBAVAL] [char](20) NULL,
	[DOMSUBAOBS] [varchar](5120) NULL,
 CONSTRAINT [PK_DOMSUBAIDD] PRIMARY KEY CLUSTERED ([DOMSUBAIDD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [adm].[DOMSUB] WITH CHECK ADD CONSTRAINT [FK_DOMSUB_DOMSUBTIC] FOREIGN KEY([DOMSUBTIC]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[DOMSUB] CHECK CONSTRAINT [FK_DOMSUB_DOMSUBTIC]
GO

CREATE TRIGGER [adm].[DOMSUB_INSERT] 
	ON [adm].[DOMSUB]
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMSUBA] (DOMSUBAMET, DOMSUBAUSU, DOMSUBAFEC, DOMSUBADIP, DOMSUBACOD, DOMSUBAEST, DOMSUBATIC, DOMSUBAORD, DOMSUBANOI, DOMSUBANOC, DOMSUBANOP, DOMSUBAPAT, DOMSUBAVAL, DOMSUBAOBS)
		SELECT 'INSERT AFTER', i.DOMSUBAUS, GETDATE(), i.DOMSUBAIP, i.DOMSUBCOD, i.DOMSUBEST, i.DOMSUBTIC, i.DOMSUBORD, i.DOMSUBNOI, i.DOMSUBNOC, i.DOMSUBNOP, i.DOMSUBPAT, i.DOMSUBVAL, i.DOMSUBOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[DOMSUB_UPDATE] 
	ON [adm].[DOMSUB]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMSUBA] (DOMSUBAMET, DOMSUBAUSU, DOMSUBAFEC, DOMSUBADIP, DOMSUBACOD, DOMSUBAEST, DOMSUBATIC, DOMSUBAORD, DOMSUBANOI, DOMSUBANOC, DOMSUBANOP, DOMSUBAPAT, DOMSUBAVAL, DOMSUBAOBS)
		SELECT 'UPDATE BEFORE', d.DOMSUBAUS, GETDATE(), d.DOMSUBAIP, d.DOMSUBCOD, d.DOMSUBEST, d.DOMSUBTIC, d.DOMSUBORD, d.DOMSUBNOI, d.DOMSUBNOC, d.DOMSUBNOP, d.DOMSUBPAT, d.DOMSUBVAL, d.DOMSUBOBS FROM DELETED d;

		INSERT INTO [adm].[DOMSUBA] (DOMSUBAMET, DOMSUBAUSU, DOMSUBAFEC, DOMSUBADIP, DOMSUBACOD, DOMSUBAEST, DOMSUBATIC, DOMSUBAORD, DOMSUBANOI, DOMSUBANOC, DOMSUBANOP, DOMSUBAPAT, DOMSUBAVAL, DOMSUBAOBS)
		SELECT 'UPDATE AFTER', i.DOMSUBAUS, GETDATE(), i.DOMSUBAIP, i.DOMSUBCOD, i.DOMSUBEST, i.DOMSUBTIC, i.DOMSUBORD, i.DOMSUBNOI, i.DOMSUBNOC, i.DOMSUBNOP, i.DOMSUBPAT, i.DOMSUBVAL, i.DOMSUBOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[DOMSUB_DELETE] 
	ON [adm].[DOMSUB]
	AFTER DELETE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[DOMSUBA] (DOMSUBAMET, DOMSUBAUSU, DOMSUBAFEC, DOMSUBADIP, DOMSUBACOD, DOMSUBAEST, DOMSUBATIC, DOMSUBAORD, DOMSUBANOI, DOMSUBANOC, DOMSUBANOP, DOMSUBAPAT, DOMSUBAVAL, DOMSUBAOBS)
		SELECT 'DELETE BEFORE', d.DOMSUBAUS, GETDATE(), d.DOMSUBAIP, d.DOMSUBCOD, d.DOMSUBEST, d.DOMSUBTIC, d.DOMSUBORD, d.DOMSUBNOI, d.DOMSUBNOC, d.DOMSUBNOP, d.DOMSUBPAT, d.DOMSUBVAL, d.DOMSUBOBS FROM DELETED d;
	END
GO