CREATE SCHEMA [covid19]
GO

CREATE TABLE [exa].[COVFICC](
	[COVFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[COVFICEST] [char](1) NOT NULL,
    [COVFICTCC] [int] NOT NULL,
    [COVFICDIC] [char](50) NOT NULL,
    [COVFICCOC] [int] NOT NULL,
    [COVFICENC] [int] NOT NULL,
    [COVFICEQC] [int] NOT NULL,
    [COVFICJUC] [int] NOT NULL,
    [COVFICPER] [int] NOT NULL,
    [COVFICFE1] [date] NULL,
    [COVFICFE2] [date] NULL,
    [COVFICFE3] [date] NULL,
    [COVFICACA] [int] NULL,
    [COVFICMCA] [int] NULL,
    [COVFICCIU] [varchar](100) NULL,
    [COVFICOBS] [varchar](5120) NULL,
    [COVFICAUS] [char](50) NOT NULL,
	[COVFICAFH] [datetime] NOT NULL,
	[COVFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_COVFICCOD] PRIMARY KEY CLUSTERED ([COVFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [exa].[COVPRUC](
	[COVPRUCOD] [int] IDENTITY(1,1) NOT NULL,
	[COVPRUTPC] [int] NOT NULL,
    [COVPRUCOC] [int] NOT NULL,
    [COVPRUVAL] [varchar](5120) NULL,
    [COVPRUAUS] [char](50) NOT NULL,
	[COVPRUAFH] [datetime] NOT NULL,
	[COVPRUAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_COVPRUCOD] PRIMARY KEY CLUSTERED ([COVPRUCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO