CREATE SCHEMA [adm]
GO

CREATE TABLE [adm].[DOMFIC](
	[DOMFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICEST] [char](1) NOT NULL,
	[DOMFICORD] [int] NULL,
	[DOMFICNOM] [varchar](100) NOT NULL,
	[DOMFICVAL] [char](20) NOT NULL,
	[DOMFICOBS] [varchar](5120) NULL,
	[DOMFICAUS] [char](20) NOT NULL,
	[DOMFICAFH] [datetime] NOT NULL,
	[DOMFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_DOMFICCOD] PRIMARY KEY CLUSTERED ([DOMFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[DOMFICA](
	[DOMFICACOD] [int] IDENTITY(1,1) NOT NULL,
	[DOMFICAMET] [char](20) NOT NULL,
	[DOMFICAUSU] [char](20) NOT NULL,
	[DOMFICAFEC] [datetime] NOT NULL,
	[DOMFICADIP] [char](20) NOT NULL,
	[DOMFICACODOLD] [int] NULL,
	[DOMFICAESTOLD] [char](1) NULL,
	[DOMFICAORDOLD] [int] NULL,
	[DOMFICANOMOLD] [varchar](100) NULL,
	[DOMFICAVALOLD] [char](20) NULL,
	[DOMFICAOBSOLD] [varchar](5120) NULL,
	[DOMFICACODNEW] [int] NULL,
	[DOMFICAESTNEW] [char](1) NULL,
	[DOMFICAORDNEW] [int] NULL,
	[DOMFICANOMNEW] [varchar](100) NULL,
	[DOMFICAVALNEW] [char](20) NULL,
	[DOMFICAOBSNEW] [varchar](5120) NULL,
 CONSTRAINT [PK_DOMFICACOD] PRIMARY KEY CLUSTERED ([DOMFICACOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO