CREATE TABLE [exa].[EXATES](
	[EXATESCOD] [int] IDENTITY(1,1) NOT NULL,
	[EXATESTTC] [int] NOT NULL,
    [EXATESEXC] [int] NOT NULL,
    [EXATESVAL] [varchar](100) NULL,
	[EXATESOBS] [varchar](MAX) NULL,
    [EXATESAUS] [char](50) NOT NULL,
	[EXATESAFH] [datetime] NOT NULL,
	[EXATESAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_EXATESOD] PRIMARY KEY CLUSTERED ([EXATESCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO