CREATE SCHEMA [lesion]
GO

CREATE TABLE [lesion].[LESFIC](
	[LESFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[LESFICESC] [int] NOT NULL, --ESTADO
    [LESFICCOC] [int] NOT NULL, --COMPETENCIA
    [LESFICJUC] [int] NOT NULL, --JUEGO
    [LESFICEQC] [int] NOT NULL, --EQUIPO
    [LESFICPEC] [int] NOT NULL, --JUGADOR
    [LESFICFEC] [datetime] NOT NULL, --FECHA

    [LESFICCLI] [int] NULL, --CLIMA
    [LESFICTEM] [decimal](3,2) NULL, --TEMPERATURA
    [LESFICDIS] [int] NULL, --DISTANCIA
    [LESFICTRA] [int] NULL, --TRANSPORTE

    [LESFICPOS] [int] NULL, --POSICION
    [LESFICTIE] [int] NULL, --TIEMPO

    [LESFICCAM] [int] NULL, --CAMPO

    


	[LESFICOBS] [varchar](5120) NULL,
	[LESFICAUS] [char](20) NOT NULL,
	[LESFICAFH] [datetime] NOT NULL,
	[LESFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_LESFICCOD] PRIMARY KEY CLUSTERED ([LESFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICESC] FOREIGN KEY([LESFICESC]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICESC]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICCOC] FOREIGN KEY([LESFICCOC]) REFERENCES [comet].[competitions] ([competitionFifaId])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICCOC]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICJUC] FOREIGN KEY([LESFICJUC]) REFERENCES [comet].[matches] ([matchFifaId])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICJUC]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICEQC] FOREIGN KEY([LESFICEQC]) REFERENCES [comet].[teams] ([teamFifaId])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICEQC]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICPEC] FOREIGN KEY([LESFICPEC]) REFERENCES [comet].[persons] ([personFifaId])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICPEC]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICCLI] FOREIGN KEY([LESFICCLI]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICCLI]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICDIS] FOREIGN KEY([LESFICDIS]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICDIS]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICTRA] FOREIGN KEY([LESFICTRA]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICTRA]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICPOS] FOREIGN KEY([LESFICPOS]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICPOS]
GO

ALTER TABLE [lesion].[LESFIC] WITH CHECK ADD CONSTRAINT [FK_LESFIC_LESFICCAM] FOREIGN KEY([LESFICCAM]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [lesion].[LESFIC] CHECK CONSTRAINT [FK_LESFIC_LESFICCAM]
GO