CREATE SCHEMA [lesion]
GO

CREATE TABLE [adm].[LESFIC](
	[LESFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[LESFICESC] [int] NOT NULL, --ESTADO
    [LESFICCOC] [int] NOT NULL, --COMPETENCIA
    [LESFICJUC] [int] NOT NULL, --JUEGO
    [LESFICEQC] [int] NOT NULL, --EQUIPO
    [LESFICPEC] [int] NOT NULL, --JUGADOR
    [LESFICFEC] [datetime] NOT NULL, --FECHA

    [LESFICCLI] [int] NULL, --CLIMA
    [LESFICTEM] [decimal](3,2) NULL, --TEMPERATURA
    [LESFICDIS] [int] NULL, --DISTANCIA
    [LESFICTRA] [int] NULL, --TRANSPORTE

    [LESFICPOS] [int] NULL, --POSICION
    [LESFICTIE] [int] NULL, --TIEMPO

    [LESFICCAM] [int] NULL, --CAMPO

    


	[LESFICOBS] [varchar](5120) NULL,
	[LESFICAUS] [char](20) NOT NULL,
	[LESFICAFH] [datetime] NOT NULL,
	[LESFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_LESFICCOD] PRIMARY KEY CLUSTERED ([LESFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO