CREATE TABLE [adm].[PERFIC](
	[PERFICCOD] [int] IDENTITY(1,1) NOT NULL,
	[PERFICEST] [int] NOT NULL,
	[PERFICTIP] [int] NOT NULL,
    [PERFICROL] [int] NOT NULL,
    [PERFICEQU] [int] NOT NULL,
	[PERFICCAT] [int] NOT NULL,
	[PERFICNOM] [varchar](100) NOT NULL,
    [PERFICUSE] [varchar](100) NOT NULL,
    [PERFICCON] [varchar](MAX) NOT NULL,
	[PERFICPAT] [varchar](100) NULL,
    [PERFICMAI] [varchar](100) NOT NULL,
    [PERFICTEF] [varchar](100) NULL,
	[PERFICOBS] [varchar](5120) NULL,
	[PERFICAUS] [char](20) NOT NULL,
	[PERFICAFH] [datetime] NOT NULL,
	[PERFICAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_PERFICCOD] PRIMARY KEY CLUSTERED ([PERFICCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [adm].[PERFICA](
	[PERFICAIDD] [int] IDENTITY(1,1) NOT NULL,
    [PERFICAMET] [char](20) NOT NULL,
	[PERFICAUSU] [char](20) NOT NULL,
	[PERFICAFEC] [datetime] NOT NULL,
	[PERFICADIP] [char](20) NOT NULL,
    [PERFICACOD] [int] NULL,
	[PERFICAEST] [int] NULL,
	[PERFICATIP] [int] NULL,
    [PERFICAROL] [int] NULL,
    [PERFICAEQU] [int] NULL,
	[PERFICACAT] [int] NULL,
	[PERFICANOM] [varchar](100) NULL,
    [PERFICAUSE] [varchar](100) NULL,
    [PERFICACON] [varchar](MAX) NULL,
	[PERFICAPAT] [varchar](100) NULL,
    [PERFICAMAI] [varchar](100) NULL,
    [PERFICATEF] [varchar](100) NULL,
	[PERFICAOBS] [varchar](5120) NULL,
 CONSTRAINT [PK_PERFICAIDD] PRIMARY KEY CLUSTERED ([PERFICAIDD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [FK_PERFIC_PERFICEST] FOREIGN KEY([PERFICEST]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[PERFIC] CHECK CONSTRAINT [FK_PERFIC_PERFICEST]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [FK_PERFIC_PERFICTIP] FOREIGN KEY([PERFICTIP]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[PERFIC] CHECK CONSTRAINT [FK_PERFIC_PERFICTIP]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [FK_PERFIC_PERFICROL] FOREIGN KEY([PERFICROL]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[PERFIC] CHECK CONSTRAINT [FK_PERFIC_PERFICROL]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [FK_PERFIC_PERFICEQU] FOREIGN KEY([PERFICEQU]) REFERENCES [comet].[teams] ([teamFifaId])
GO
ALTER TABLE [adm].[PERFIC] CHECK CONSTRAINT [FK_PERFIC_PERFICEQU]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [FK_PERFIC_PERFICCAT] FOREIGN KEY([PERFICCAT]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[PERFIC] CHECK CONSTRAINT [FK_PERFIC_PERFICCAT]
GO

ALTER TABLE [adm].[PERFIC] WITH CHECK ADD CONSTRAINT [UQ_PERFIC_PERFICUSE] UNIQUE([PERFICEQU])
GO

CREATE TRIGGER [adm].[PERFIC_INSERT] 
	ON [adm].[PERFIC]
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[PERFICA] (PERFICAMET, PERFICAUSU, PERFICAFEC, PERFICADIP, PERFICACOD, PERFICAEST, PERFICATIP, PERFICAROL, PERFICAEQU, PERFICACAT, PERFICANOM, PERFICAUSE, PERFICACON, PERFICAPAT, PERFICAMAI, PERFICATEF, PERFICAOBS)
		SELECT 'INSERT AFTER', i.PERFICAUS, GETDATE(), i.PERFICAIP, i.PERFICCOD, i.PERFICEST, i.PERFICTIP, i.PERFICROL, i.PERFICEQU, i.PERFICCAT, i.PERFICNOM, i.PERFICUSE, i.PERFICCON, i.PERFICPAT, i.PERFICMAI, i.PERFICTEF, i.PERFICOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[PERFIC_UPDATE] 
	ON [adm].[PERFIC]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[PERFICA] (PERFICAMET, PERFICAUSU, PERFICAFEC, PERFICADIP, PERFICACOD, PERFICAEST, PERFICATIP, PERFICAROL, PERFICAEQU,  PERFICACAT, PERFICANOM, PERFICAUSE, PERFICACON, PERFICAPAT, PERFICAMAI, PERFICATEF, PERFICAOBS)
        SELECT 'UPDATE BEFORE', d.PERFICAUS, GETDATE(), d.PERFICAIP, d.PERFICCOD, d.PERFICEST, d.PERFICTIP, d.PERFICROL, d.PERFICEQU, d.PERFICCAT, d.PERFICNOM, d.PERFICUSE, d.PERFICCON, d.PERFICPAT, d.PERFICMAI, d.PERFICTEF, d.PERFICOBS FROM DELETED d;

		INSERT INTO [adm].[PERFICA] (PERFICAMET, PERFICAUSU, PERFICAFEC, PERFICADIP, PERFICACOD, PERFICAEST, PERFICATIP, PERFICAROL, PERFICAEQU,  PERFICACAT, PERFICANOM, PERFICAUSE, PERFICACON, PERFICAPAT, PERFICAMAI, PERFICATEF, PERFICAOBS)
        SELECT 'UPDATE AFTER', i.PERFICAUS, GETDATE(), i.PERFICAIP, i.PERFICCOD, i.PERFICEST, i.PERFICTIP, i.PERFICROL, i.PERFICEQU, i.PERFICCAT, i.PERFICNOM, i.PERFICUSE, i.PERFICCON, i.PERFICPAT, i.PERFICMAI, i.PERFICTEF, i.PERFICOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[PERFIC_DELETE] 
	ON [adm].[PERFIC]
	AFTER DELETE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [adm].[PERFICA] (PERFICAMET, PERFICAUSU, PERFICAFEC, PERFICADIP, PERFICACOD, PERFICAEST, PERFICATIP, PERFICAROL, PERFICAEQU,  PERFICACAT, PERFICANOM, PERFICAUSE, PERFICACON, PERFICAPAT, PERFICAMAI, PERFICATEF, PERFICAOBS)
        SELECT 'DELETE BEFORE', d.PERFICAUS, GETDATE(), d.PERFICAIP, d.PERFICCOD, d.PERFICEST, d.PERFICTIP, d.PERFICROL, d.PERFICEQU, d.PERFICCAT, d.PERFICNOM, d.PERFICUSE, d.PERFICCON, d.PERFICPAT, d.PERFICMAI, d.PERFICTEF, d.PERFICOBS FROM DELETED d;
	END
GO