CREATE SCHEMA [aud]
GO

CREATE TABLE [adm].[PERCOM](
	[PERCOMCOC] [int] NOT NULL,
	[PERCOMPEC] [int] NOT NULL,
	[PERCOMTMC] [int] NOT NULL,
	[PERCOMOBS] [varchar](5120) NULL,
	[PERCOMAUS] [char](50) NOT NULL,
	[PERCOMAFE] [datetime] NOT NULL,
	[PERCOMAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_PERCOMCOC_PERCOMPEC_PERCOMTMC] PRIMARY KEY CLUSTERED ([PERCOMCOC] ASC, [PERCOMPEC] ASC, [PERCOMTMC] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [aud].[PERCOM](
	[PERCOMIDD] [int] IDENTITY(1,1) NOT NULL,
    [PERCOMAME] [char](20) NOT NULL,
	[PERCOMAUS] [char](50) NOT NULL,
	[PERCOMAFE] [datetime] NOT NULL,
	[PERCOMAIP] [char](20) NOT NULL,
    [PERCOMCOC] [int] NOT NULL,
	[PERCOMPEC] [int] NOT NULL,
	[PERCOMTMC] [int] NOT NULL,
	[PERCOMOBS] [varchar](5120) NULL,
 CONSTRAINT [PK_PERCOMAIDD] PRIMARY KEY CLUSTERED ([PERCOMAIDD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

ALTER TABLE [adm].[PERCOM] WITH CHECK ADD CONSTRAINT [FK_PERCOMCOC] FOREIGN KEY([PERCOMCOC]) REFERENCES [comet].[competitions] ([competitionFifaId])
GO
ALTER TABLE [adm].[PERCOM] CHECK CONSTRAINT [FK_PERCOMCOC]
GO

ALTER TABLE [adm].[PERCOM] WITH CHECK ADD CONSTRAINT [FK_PERCOMPEC] FOREIGN KEY([PERCOMPEC]) REFERENCES [adm].[PERFIC] ([PERFICCOD])
GO
ALTER TABLE [adm].[PERCOM] CHECK CONSTRAINT [FK_PERCOMPEC]
GO

ALTER TABLE [adm].[PERCOM] WITH CHECK ADD CONSTRAINT [FK_PERCOMTMC] FOREIGN KEY([PERCOMTMC]) REFERENCES [adm].[DOMFIC] ([DOMFICCOD])
GO
ALTER TABLE [adm].[PERCOM] CHECK CONSTRAINT [FK_PERCOMTMC]
GO

CREATE TRIGGER [adm].[PERCOM_INSERT] 
	ON [adm].[PERCOM]
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[PERCOM] (PERCOMAME, PERCOMAUS, PERCOMAFE, PERCOMAIP, PERCOMCOC, PERCOMPEC, PERCOMTMC, PERCOMOBS)
		SELECT 'INSERT AFTER', i.PERCOMAUS, GETDATE(), i.PERCOMAIP, i.PERCOMCOC, i.PERCOMPEC, i.PERCOMTMC, i.PERCOMOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[PERCOM_UPDATE] 
	ON [adm].[PERCOM]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[PERCOM] (PERCOMAME, PERCOMAUS, PERCOMAFE, PERCOMAIP, PERCOMCOC, PERCOMPEC, PERCOMTMC, PERCOMOBS)
		SELECT 'UPDATE BEFORE', d.PERCOMAUS, GETDATE(), d.PERCOMAIP, d.PERCOMCOC, d.PERCOMPEC, d.PERCOMTMC, d.PERCOMOBS FROM DELETED d;

		INSERT INTO [aud].[PERCOM] (PERCOMAME, PERCOMAUS, PERCOMAFE, PERCOMAIP, PERCOMCOC, PERCOMPEC, PERCOMTMC, PERCOMOBS)
		SELECT 'UPDATE AFTER', i.PERCOMAUS, GETDATE(), i.PERCOMAIP, i.PERCOMCOC, i.PERCOMPEC, i.PERCOMTMC, i.PERCOMOBS FROM INSERTED i;
	END
GO

CREATE TRIGGER [adm].[PERCOM_DELETE] 
	ON [adm].[PERCOM]
	AFTER DELETE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[PERCOM] (PERCOMAME, PERCOMAUS, PERCOMAFE, PERCOMAIP, PERCOMCOC, PERCOMPEC, PERCOMTMC, PERCOMOBS)
		SELECT 'DELETE BEFORE', d.PERCOMAUS, GETDATE(), d.PERCOMAIP, d.PERCOMCOC, d.PERCOMPEC, d.PERCOMTMC, d.PERCOMOBS FROM DELETED d;
	END
GO